name: Auto-Merge Knowl Docs
description: Auto-Merge Knowl Docs
inputs:
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
runs:
  using: composite
  steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      shell: bash
    - name: Setup Environment (Push)  
      run: |  
        echo "REPO_NAME=${{ github.event.repository.name }}" >> ${GITHUB_ENV}
        echo "OWNER_NAME=${{ github.repository_owner }}" >> ${GITHUB_ENV}
        echo "KNOWL_BACKEND_HTTP=https://staging-api.knowl.io/" >> ${GITHUB_ENV}
        echo "${{ github.action_path }}" >> "$GITHUB_PATH"
      shell: bash
