name: Generate AI docs
description: Generate AI doc
inputs:
  OPENAI_API_KEY:
    description: OPENAI_API_KEY
    required: true
  KNOWL_API_KEY:
    description: KNOWL_API_KEY
    required: true
runs:
  using: composite
  steps:
    - name: Setup Environment (Push)  
      run: |  
        echo "COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
        echo "${{ github.action_path }}" >> "$GITHUB_PATH"
        shell: bash
    - name: setup python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv
      shell: bash
    - name: Prepare script file
      run: chmod +x "${{ github.action_path }}/run-gen-docs.sh"
      shell: bash
    - name: Run script file
      run: run-gen-docs.sh ${{ github.workspace }} "files_diff.json"
      shell: bash
      env:
        OPENAI_API_KEY: ${{inputs.OPENAI_API_KEY}}
        KNOWL_API_KEY: ${{inputs.KNOWL_API_KEY}}
